import { ArtifactsDir, getCwd } from '@contentlayer/core'
import { OT, pipe, T } from '@contentlayer/utils/effect'
import { fs } from '@contentlayer/utils/node'
import * as path from 'path'

import { BaseCommand } from './_BaseCommand.js'

export class PostInstallCommand extends BaseCommand {
  static paths = [['postinstall']]

  executeSafe = pipe(
    T.gen(function* ($) {
      const artifactsDirPath = yield* $(ArtifactsDir.mkdir)

      yield* $(T.forEachPar_(['data', 'types'], (moduleName) => makeModuleStub({ artifactsDirPath, moduleName })))

      yield* $(createSymlinkForDotpkg({ artifactsDirPath }))
      yield* $(addToplevelDotpkgToGitignore())
    }),
    OT.withSpan('@contentlayer/cli/commands/PostInstallCommand:executeSafe', { attributes: { cwd: process.cwd() } }),
  )
}

const makeModuleStub = ({ artifactsDirPath, moduleName }: { artifactsDirPath: string; moduleName: string }) =>
  T.gen(function* ($) {
    const dirPath = path.join(artifactsDirPath, moduleName)
    const dirExists = yield* $(fs.fileOrDirExists(dirPath))
    if (!dirExists) {
      yield* $(fs.mkdirp(dirPath))
    }

    const dtsFilePath = path.join(dirPath, 'index.d.ts')
    const dtsFileExists = yield* $(fs.fileOrDirExists(dtsFilePath))
    if (!dtsFileExists) {
      yield* $(fs.writeFile(dtsFilePath, moduleStubFile))
    }
  })

const moduleStubFile = `\
// This file is automatically generated by the Contentlayer.
// This is a placeholder until \`contentlayer build\` has been run.

export {}
`

const createSymlinkForDotpkg = ({ artifactsDirPath }: { artifactsDirPath: string }) =>
  T.gen(function* ($) {
    const cwd = yield* $(getCwd)
    const symlinkPath = path.join(cwd, '.contentlayer')
    // NOTE dir-symlinks are interpreted as dirs by the OS
    const symlinkExists = yield* $(fs.fileOrDirExists(symlinkPath))
    if (!symlinkExists) {
      yield* $(fs.symlink({ symlinkPath, targetPath: artifactsDirPath, type: 'dir' }))
    }
  })

const addToplevelDotpkgToGitignore = () =>
  T.gen(function* ($) {
    const cwd = yield* $(getCwd)
    const gitignoreFilePath = path.join(cwd, '.gitignore')
    const gitignoreExists = yield* $(fs.fileOrDirExists(gitignoreFilePath))
    if (gitignoreExists) {
      const gitignoreContent = yield* $(fs.readFile(gitignoreFilePath))

      if (!gitignoreContent.includes('.contentlayer')) {
        const newGitignoreContent = `\
${gitignoreContent}

# Contentlayer
.contentlayer
`

        yield* $(fs.writeFile(gitignoreFilePath, newGitignoreContent))
      }
    }
  })
