/** @type { import('@jest/types').Config.InitialOptions } */

const esmModules = [
  'rehype-stringify',
  'hast-util-to-html',
  'hast-util-is-element',
  'mdast-util-to-string',
  'property-information',
  'html-void-elements',
  'unist-util-is',
  'hast-util-whitespace',
  'space-separated-tokens',
  'comma-separated-tokens',
  'stringify-entities',
  'character-entities-legacy',
  'micromark-util-chunked',
  'character-entities',
  'micromark-factory-space',
  'micromark-util-character',
  'micromark-core-commonmark',
  'micromark-util-subtokenize',
  'micromark-factory-title',
  'micromark-factory-destination',
  'micromark-factory-label',
  'micromark-util-classify-character',
  'micromark-util-resolve-all',
  'parse-entities',
  'character-entities-html4',
  'ccount',
  'remark-parse',
  'mdast-util-from-markdown',
  'micromark',
  'micromark-util-combine-extensions',
].join('|')

export default {
  displayName: 'source-files',
  testEnvironment: 'node',
  transform: {
    // '.+\\.jsx?$': 'esbuild-jest',
  },
  // transformIgnorePatterns: [`node_modules/(?!(${esmModules})/)`],
  testRegex: 'dist/esm/.*spec.js',
  // snapshotResolver: '<rootDir>/dist/cjs/__test__/__scripts__/snapshotResolver.js',
  // resolver: '<rootDir>/dist/esm/__test__/__scripts__/resolver.js',
}
