import * as utils from '@contentlayer/utils'

import type { DocumentTypeDef } from '../schema/index.js'

export const autogeneratedNote = `NOTE This file is auto-generated by Contentlayer`

export const getDataVariableName = ({ docDef }: { docDef: DocumentTypeDef }): string => {
  if (docDef.isSingleton) {
    return utils.lowercaseFirstChar(utils.inflection.singularize(docDef.name))
  } else {
    return 'all' + utils.uppercaseFirstChar(utils.inflection.pluralize(docDef.name))
  }
}
