name: 'Checkout and run yarn'
description: 'This action checks out the commit, sets up Node and installs deps using yarn.'
author: 'schickling'
runs:
  using: 'composite'
  steps:
    - name: Support longpaths (needed for Windows)
      run: git config --global core.longpaths true
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn install
