// NOTE This file is auto-generated by the Sourcebit CLI

export type Image = string

export interface SourcebitGenTypes {
  types: Types
  typeMap: TypeMap
  typeNames: TypeNames
}

declare global {
  interface SourcebitGen extends SourcebitGenTypes {}
}

export type TypeMap = {
  landing: landing
  page: page
  blog: blog
  post: post
  person: person
  blog_category: blog_category
  site_config: site_config
  sanity_imageAsset: sanity_imageAsset
  sanity_fileAsset: sanity_fileAsset
}

export type Types = landing | page | blog | post | person | blog_category | site_config | sanity_imageAsset | sanity_fileAsset
export type TypeNames = Types['__meta']['typeName']

/** Document types */



export type landing = {
  __meta: {
    typeName: 'landing'
    sourceFilePath: string
  }

  /** The title of the page */
  title: string | undefined
  /** The URL path of this page relative to the site domain */
  slug: 'todo slug' | undefined
  /** Page sections */
  sections: section_cta | section_contact | section_content | section_faq | section_features | section_hero | section_posts | section_pricing | section_reviews[] | undefined
}

export type page = {
  __meta: {
    typeName: 'page'
    sourceFilePath: string
  }

  /** The title of the page */
  title: string | undefined
  /** The URL path of this page relative to the site domain */
  slug: 'todo slug' | undefined
  /** The text shown below the page title */
  subtitle: 'todo text' | undefined
  /** The image shown below the page title */
  image: Image | undefined
  /** Page content */
  content: 'todo markdown' | undefined
}

export type blog = {
  __meta: {
    typeName: 'blog'
    sourceFilePath: string
  }

  /** The title of the page */
  title: string | undefined
  /** The URL path of this page relative to the site domain */
  slug: 'todo slug' | undefined
}

export type post = {
  __meta: {
    typeName: 'post'
    sourceFilePath: string
  }

  /** The title of the post */
  title: string | undefined
  /** The URL path of this page relative to the site domain */
  slug: 'todo slug' | undefined
  date: Date | undefined
  /** The author of the post */
  author: person | undefined
  /** Categories this blog relate to */
  categories: blog_category[] | undefined
  /** The text shown just below the title or the featured image */
  subtitle: 'todo text' | undefined
  /** The image shown below the title */
  image: Image | undefined
  /** The image shown in the blog feed */
  thumb_image: Image | undefined
  /** The excerpt of the post displayed in the blog feed */
  excerpt: 'todo markdown' | undefined
  /** Post content */
  content: 'todo markdown' | undefined
}

export type person = {
  __meta: {
    typeName: 'person'
    sourceFilePath: string
  }

  first_name: string | undefined
  last_name: string | undefined
  /** The photo of the person */
  photo: Image | undefined
  bio: 'todo markdown' | undefined
}

export type blog_category = {
  __meta: {
    typeName: 'blog_category'
    sourceFilePath: string
  }

  /** The title of the category */
  title: string | undefined
  /** The slug of the category */
  slug: 'todo slug' | undefined
}

export type site_config = {
  __meta: {
    typeName: 'site_config'
    sourceFilePath: string
  }

  /** Site title */
  title: string | undefined
  /** The color palette of the site */
  palette: string | undefined
  header: header | undefined
  footer: footer | undefined
}

export type sanity_imageAsset = {
  __meta: {
    typeName: 'sanity_imageAsset'
    sourceFilePath: string
  }

  originalFilename: string | undefined
  label: string | undefined
  title: string | undefined
  description: string | undefined
  sha1hash: string | undefined
  extension: string | undefined
  mimeType: string | undefined
  size: 'todo number' | undefined
  assetId: string | undefined
  path: string | undefined
  url: string | undefined
  metadata: sanity_imageMetadata | undefined
  source: sanity_assetSourceData | undefined
}

export type sanity_fileAsset = {
  __meta: {
    typeName: 'sanity_fileAsset'
    sourceFilePath: string
  }

  originalFilename: string | undefined
  label: string | undefined
  title: string | undefined
  description: string | undefined
  sha1hash: string | undefined
  extension: string | undefined
  mimeType: string | undefined
  size: 'todo number' | undefined
  assetId: string | undefined
  path: string | undefined
  url: string | undefined
  source: sanity_assetSourceData | undefined
}

/** Object types */



export type color = {
  __meta: {
    typeName: 'color'
  }
  hex: string | undefined
  alpha: 'todo number' | undefined
  hsl: hslaColor | undefined
  hsv: hsvaColor | undefined
  rgb: rgbaColor | undefined
}

export type rgbaColor = {
  __meta: {
    typeName: 'rgbaColor'
  }
  r: 'todo number' | undefined
  g: 'todo number' | undefined
  b: 'todo number' | undefined
  a: 'todo number' | undefined
}

export type hsvaColor = {
  __meta: {
    typeName: 'hsvaColor'
  }
  h: 'todo number' | undefined
  s: 'todo number' | undefined
  v: 'todo number' | undefined
  a: 'todo number' | undefined
}

export type hslaColor = {
  __meta: {
    typeName: 'hslaColor'
  }
  h: 'todo number' | undefined
  s: 'todo number' | undefined
  l: 'todo number' | undefined
  a: 'todo number' | undefined
}

export type action = {
  __meta: {
    typeName: 'action'
  }
  label: string | undefined
  url: 'todo url' | undefined
  /** Use primary color for this action */
  primary: boolean | undefined
  /** Should the link open a new tab */
  new_window: boolean | undefined
}

export type section_contact = {
  __meta: {
    typeName: 'section_contact'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The text shown below the title */
  subtitle: 'todo text' | undefined
  /** Section content, appears before contact form */
  content: 'todo markdown' | undefined
  /** The background of the section */
  background: string | undefined
}

export type section_content = {
  __meta: {
    typeName: 'section_content'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The text content of the section */
  content: 'todo markdown' | undefined
  /** The image of the section */
  image: Image | undefined
  /** The background of the section */
  background: string | undefined
  actions: action[] | undefined
}

export type section_cta = {
  __meta: {
    typeName: 'section_cta'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The subtitle of this section */
  subtitle: 'todo text' | undefined
  actions: action[] | undefined
}

export type section_faq = {
  __meta: {
    typeName: 'section_faq'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The subtitle of this section */
  subtitle: 'todo text' | undefined
  /** The background of the section */
  background: string | undefined
  faq_items: faq_item[] | undefined
}

export type faq_item = {
  __meta: {
    typeName: 'faq_item'
  }
  question: 'todo text' | undefined
  answer: 'todo markdown' | undefined
}

export type section_features = {
  __meta: {
    typeName: 'section_features'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The subtitle of this section */
  subtitle: 'todo text' | undefined
  /** The background of the section */
  background: string | undefined
  features: feature_item[] | undefined
}

export type feature_item = {
  __meta: {
    typeName: 'feature_item'
  }
  title: string | undefined
  /** Feature description */
  content: 'todo markdown' | undefined
  /** Feature image */
  image: Image | undefined
  actions: action[] | undefined
}

export type section_hero = {
  __meta: {
    typeName: 'section_hero'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The text content of the section */
  content: 'todo markdown' | undefined
  /** The image of the section */
  image: Image | undefined
  actions: action[] | undefined
}

export type section_posts = {
  __meta: {
    typeName: 'section_posts'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The subtitle of this section */
  subtitle: 'todo text' | undefined
  /** The background of the section */
  background: string | undefined
}

export type section_pricing = {
  __meta: {
    typeName: 'section_pricing'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The subtitle of this section */
  subtitle: 'todo text' | undefined
  /** The background of the section */
  background: string | undefined
  pricing_plans: pricing_plan[] | undefined
}

export type pricing_plan = {
  __meta: {
    typeName: 'pricing_plan'
  }
  title: string | undefined
  price: string | undefined
  details: 'todo markdown' | undefined
  /** Make the plan stand out by adding a distinctive style */
  highlight: boolean | undefined
  actions: action[] | undefined
}

export type section_reviews = {
  __meta: {
    typeName: 'section_reviews'
  }
  /** Element ID can be used in links to scroll the page to this section when link clicked */
  section_id: string | undefined
  /** The title of this section */
  title: string | undefined
  /** The subtitle of this section */
  subtitle: 'todo text' | undefined
  /** The background of the section */
  background: string | undefined
  reviews: review_item[] | undefined
}

export type review_item = {
  __meta: {
    typeName: 'review_item'
  }
  author: string | undefined
  avatar: Image | undefined
  content: 'todo text' | undefined
}

export type header = {
  __meta: {
    typeName: 'header'
  }
  /** The title displayed in the header if logo image not specified */
  title: string | undefined
  /** The logo image displayed in the header */
  logo_img: Image | undefined
  /** Display the navigation menu bar in the header */
  has_nav: boolean | undefined
  /** List of navigation links in header */
  nav_links: action[] | undefined
}

export type footer = {
  __meta: {
    typeName: 'footer'
  }
  /** The logo image displayed in the footer */
  logo_img: Image | undefined
  /** The tagline displayed in the footer */
  tagline: string | undefined
  /** Display the secondary navigation menu in the footer */
  has_nav: boolean | undefined
  /** The title of the secondary menu displayed in the footer */
  nav_title: string | undefined
  /** List of navigation links in footer */
  nav_links: action[] | undefined
  /** Display social links in the footer */
  has_social: boolean | undefined
  /** The title of the social links list displayed in the footer */
  social_title: string | undefined
  /** List of social links displayed in the footer */
  social_links: action[] | undefined
  /** Display the newsletter subscription form in the footer */
  has_subscribe: boolean | undefined
  /** The title of the subscribe block displayed in the footer */
  subscribe_title: string | undefined
  /** The text content in the subscribe block displayed in the footer */
  subscribe_content: string | undefined
  /** The copyright text displayed in the footer */
  content: string | undefined
  links: action[] | undefined
}

export type sanity_assetSourceData = {
  __meta: {
    typeName: 'sanity_assetSourceData'
  }
  /** A canonical name for the source this asset is originating from */
  name: string | undefined
  /** The unique ID for the asset within the originating source so you can programatically find back to it */
  id: string | undefined
  /** A URL to find more information about this asset in the originating source */
  url: string | undefined
}

export type slug = {
  __meta: {
    typeName: 'slug'
  }
  current: string | undefined
}

export type geopoint = {
  __meta: {
    typeName: 'geopoint'
  }
  lat: 'todo number' | undefined
  lng: 'todo number' | undefined
  alt: 'todo number' | undefined
}

export type sanity_imageCrop = {
  __meta: {
    typeName: 'sanity_imageCrop'
  }
  top: 'todo number' | undefined
  bottom: 'todo number' | undefined
  left: 'todo number' | undefined
  right: 'todo number' | undefined
}

export type sanity_imageHotspot = {
  __meta: {
    typeName: 'sanity_imageHotspot'
  }
  x: 'todo number' | undefined
  y: 'todo number' | undefined
  height: 'todo number' | undefined
  width: 'todo number' | undefined
}

export type sanity_imageMetadata = {
  __meta: {
    typeName: 'sanity_imageMetadata'
  }
  location: geopoint | undefined
  dimensions: sanity_imageDimensions | undefined
  palette: sanity_imagePalette | undefined
  lqip: string | undefined
  hasAlpha: boolean | undefined
  isOpaque: boolean | undefined
}

export type sanity_imageDimensions = {
  __meta: {
    typeName: 'sanity_imageDimensions'
  }
  height: 'todo number' | undefined
  width: 'todo number' | undefined
  aspectRatio: 'todo number' | undefined
}

export type sanity_imagePalette = {
  __meta: {
    typeName: 'sanity_imagePalette'
  }
  darkMuted: sanity_imagePaletteSwatch | undefined
  lightVibrant: sanity_imagePaletteSwatch | undefined
  darkVibrant: sanity_imagePaletteSwatch | undefined
  vibrant: sanity_imagePaletteSwatch | undefined
  dominant: sanity_imagePaletteSwatch | undefined
  lightMuted: sanity_imagePaletteSwatch | undefined
  muted: sanity_imagePaletteSwatch | undefined
}

export type sanity_imagePaletteSwatch = {
  __meta: {
    typeName: 'sanity_imagePaletteSwatch'
  }
  background: string | undefined
  foreground: string | undefined
  population: 'todo number' | undefined
  title: string | undefined
}
